language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update ${COMPOSER_FLAGS} --prefer-dist

script: 
  - phpunit

matrix:
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-lowest"
